#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "c9890f560fc241eea92b61878830d3c4" }
]
